"""
THE UNIVERSE HAS NO NOW — shot list + narration.

Each shot: id, scene (renderer name), params, min_dur (seconds of picture even
without narration), lead (silence before the first line), tail (silence after the
last line), lines (narration sentences with pause_after), transition into the
NEXT shot ('cut' | 'dissolve:<sec>' | 'dip:<sec>'), sfx cues (local time -> name).

Narration is synthesised per sentence so that caption timing is exact and the
rhythm (pauses) is under editorial control.
"""

ACTS = {
    1: "THE SAME MOMENT",
    2: "TIME IS NOT WHAT YOU THINK",
    3: "LIGHT",
    4: "GRAVITY REWRITES THE STAGE",
    5: "THE EDGE OF THE BLACK HOLE",
    6: "THEN QUANTUM PHYSICS ARRIVED",
    7: "ENTANGLEMENT",
    8: "TWO GREAT THEORIES",
    9: "THE UNKNOWN",
    10: "THE SAME MOMENT, AGAIN",
}

PAUSE_SCALE = 0.75
TAIL_SCALE = 0.75

def L(text, pause=0.7, **kw):
    d = {"text": text, "pause": round(pause * PAUSE_SCALE, 3)}
    d.update(kw)
    return d

SHOTS = [
 # ---------------------------------------------------------------- ACT I
 dict(id="S01", act=1, scene="card", params=dict(text="Imagine two events happening\nat exactly the same time.", style="quote"),
      min_dur=6.0, lead=0.0, tail=0.0, lines=[], trans="dip:1.2",
      notes="Absolute silence. Black. The sentence fades in letter-group by letter-group."),
 dict(id="S02", act=1, scene="two_clocks", params=dict(mode="sync", labels=("A", "B")),
      min_dur=9.0, lead=1.2, tail=0.6,
      lines=[L("Two clocks.", 0.9), L("Two places.", 0.9), L("One moment.", 1.4)],
      trans="cut", sfx={0.0: "tick_loop"},
      notes="Two thin-ring clocks, identical, ticking in unison. Slow push-in."),
 dict(id="S03", act=1, scene="two_clocks", params=dict(mode="sync_wide"),
      min_dur=6.0, lead=0.3, tail=0.8,
      lines=[L("It feels like the simplest idea in the world: everyone, everywhere, shares the same now.", 1.0)],
      trans="cut",
      notes="Wide: the clocks are small against a dark field; a faint horizon line connects them."),
 dict(id="S04", act=1, scene="two_clocks", params=dict(mode="doubt"),
      min_dur=5.0, lead=0.4, tail=1.2,
      lines=[L("It is not simple.", 0.9), L("And strictly speaking, it is not true.", 1.0)],
      trans="dip:0.8", sfx={0.2: "sub_drop"},
      notes="The tick loop stops. One clock's second hand hesitates."),
 dict(id="S05", act=1, scene="card", params=dict(text="1905", style="year", sub="ON THE ELECTRODYNAMICS OF MOVING BODIES"),
      min_dur=5.0, lead=0.6, tail=0.4,
      lines=[L("In 1905, Einstein began with two facts that had been measured, but not understood.", 0.8)],
      trans="cut"),
 dict(id="S06", act=1, scene="postulates", params=dict(),
      min_dur=12.0, lead=0.2, tail=0.8,
      lines=[L("The laws of physics look the same to anyone moving at constant velocity.", 0.8),
             L("And light, in empty space, always moves at the same speed, whoever is measuring it.", 1.0)],
      trans="cut", sfx={0.3: "ui_in", 6.0: "ui_in"},
      notes="Two postulates appear as typographic plates; a ray of light crosses the frame at constant speed past observers moving at different speeds."),
 dict(id="S07", act=1, scene="postulates", params=dict(phase="give"),
      min_dur=6.0, lead=0.2, tail=0.8,
      lines=[L("Hold on to both at once, and something has to give.", 0.7),
             L("What gives is the idea of a shared now.", 1.0)],
      trans="dissolve:1.0", sfx={0.0: "pulse_low"}),
 dict(id="S08", act=1, scene="ship_flash", params=dict(frame="ship"),
      min_dur=10.0, lead=0.3, tail=0.8,
      lines=[L("Picture a flash of light released from the exact middle of a moving ship.", 0.6),
             L("For someone on board, it reaches the front and the back at the same instant.", 1.0)],
      trans="cut", sfx={3.2: "flash"},
      notes="Ship frame: the vessel is still, the light fronts expand symmetrically and hit both walls together."),
 dict(id="S09", act=1, scene="ship_flash", params=dict(frame="platform"),
      min_dur=11.0, lead=0.3, tail=0.8,
      lines=[L("For someone watching the ship pass, the back wall rushes toward the light, and the front wall runs away from it.", 0.6),
             L("The flash reaches the back first.", 1.2)],
      trans="cut", sfx={3.0: "flash"},
      notes="Platform frame: the ship slides right; the same light fronts expand around a fixed emission point; the rear wall meets the light first."),
 dict(id="S10", act=1, scene="ship_flash", params=dict(frame="both"),
      min_dur=10.0, lead=0.3, tail=1.2,
      lines=[L("Neither of them is wrong.", 0.8),
             L("The order of distant events depends on how you are moving, and no experiment can settle which of them is right.", 1.2)],
      trans="dip:1.0",
      notes="Both frames side by side, the two timings shown as two small clock readings that disagree."),

 # ---------------------------------------------------------------- ACT II
 dict(id="S11", act=2, scene="card", params=dict(text="TIME IS NOT WHAT YOU THINK", style="act", act_no="II"),
      min_dur=4.5, lead=0.4, tail=0.3,
      lines=[L("Follow the consequences, and the familiar structure of time comes apart.", 0.8)],
      trans="cut"),
 dict(id="S12", act=2, scene="light_clock", params=dict(),
      min_dur=12.0, lead=0.3, tail=0.8,
      lines=[L("A moving clock ticks more slowly, as measured by someone it moves past.", 0.8),
             L("A moving ruler is shorter along its direction of travel.", 0.8),
             L("These are not illusions. They are measurements.", 1.0)],
      trans="dissolve:1.2", sfx={0.0: "tick_light"},
      notes="A light clock: pulse bouncing between mirrors. A second copy moves; its pulse zig-zags, ticks arrive late. A ruler passes, foreshortened."),
 dict(id="S13", act=2, scene="minkowski", params=dict(phase="axes"),
      min_dur=10.0, lead=0.3, tail=0.6,
      lines=[L("To see why, physicists draw a map that no one can walk on.", 0.6),
             L("Space along one axis. Time along the other.", 0.6),
             L("Light travels at forty-five degrees.", 0.9)],
      trans="cut", sfx={2.5: "ui_in", 5.5: "ui_in"},
      notes="Spacetime diagram assembles itself: axes, grid, the light lines at 45°."),
 dict(id="S14", act=2, scene="minkowski", params=dict(phase="cones"),
      min_dur=12.0, lead=0.3, tail=0.6,
      lines=[L("Every clock traces a line through this map: its world line.", 0.7),
             L("And everything that can ever influence an event, or be influenced by it, lies inside two cones of light.", 1.0)],
      trans="cut", sfx={1.0: "pulse_low"},
      notes="World lines rise; the future and past light cones fill in."),
 dict(id="S15", act=2, scene="minkowski", params=dict(phase="elsewhere"),
      min_dur=9.0, lead=0.3, tail=0.8,
      lines=[L("Outside the cones lies a vast region of events that are neither before nor after.", 0.7),
             L("For them, 'now' is simply not defined.", 1.1)],
      trans="cut",
      notes="The 'elsewhere' region glows faintly; a label."),
 dict(id="S16", act=2, scene="minkowski", params=dict(phase="boost"),
      min_dur=12.0, lead=0.3, tail=0.8,
      lines=[L("Change your velocity, and the slice you call 'the present' tilts.", 0.8),
             L("What happens 'at the same time' on a distant star is, quite literally, a matter of perspective.", 1.2)],
      trans="dissolve:1.0", sfx={1.0: "whoosh_soft"},
      notes="A Lorentz boost: the grid shears; the simultaneity line tilts; two events swap order."),
 dict(id="S17", act=2, scene="gps", params=dict(),
      min_dur=12.0, lead=0.3, tail=1.0,
      lines=[L("This is not philosophy. It is measured every day.", 0.7),
             L("Clocks aboard GPS satellites gain about thirty-eight microseconds a day on clocks on the ground.", 0.6),
             L("Left uncorrected, your position would drift by kilometers within a day.", 1.2)],
      trans="dip:1.0", sfx={0.5: "data_tick"},
      notes="Earth, satellite orbits, a drifting position marker, the +38 µs/day readout."),

 # ---------------------------------------------------------------- ACT III
 dict(id="S18", act=3, scene="card", params=dict(text="LIGHT", style="act", act_no="III"),
      min_dur=4.0, lead=0.4, tail=0.3,
      lines=[L("So light sets the rules.", 0.5), L("Follow a single pulse, and you can measure the universe with it.", 0.8)],
      trans="cut"),
 dict(id="S19", act=3, scene="scale", params=dict(stage="atom"),
      min_dur=7.0, lead=0.6, tail=0.4,
      lines=[L("Across an atom, it takes less than a billionth of a billionth of a second.", 0.8)],
      trans="dissolve:0.7", sfx={0.2: "pulse_hi"}),
 dict(id="S20", act=3, scene="scale", params=dict(stage="human"),
      min_dur=6.0, lead=0.4, tail=0.4,
      lines=[L("Across a human body, a few billionths of a second.", 0.8)],
      trans="dissolve:0.7", sfx={0.2: "pulse_hi"},
      notes="HUMAN MOMENT: a silhouette standing in the pulse's path."),
 dict(id="S21", act=3, scene="scale", params=dict(stage="earth"),
      min_dur=7.0, lead=0.4, tail=0.4,
      lines=[L("Around the Earth, seven times in one second.", 0.9)],
      trans="dissolve:0.7", sfx={0.2: "pulse_hi"}),
 dict(id="S22", act=3, scene="scale", params=dict(stage="solar"),
      min_dur=14.0, lead=0.4, tail=0.4,
      lines=[L("To the Moon, a little over a second.", 0.5), L("To the Sun, eight minutes.", 0.5),
             L("To the Voyager probes, most of a day.", 0.9)],
      trans="dissolve:0.7", sfx={0.2: "pulse_hi"}),
 dict(id="S23", act=3, scene="scale", params=dict(stage="galaxy"),
      min_dur=14.0, lead=0.4, tail=0.4,
      lines=[L("To the nearest star, four years.", 0.5), L("Across our galaxy, a hundred thousand years.", 0.5),
             L("To the farthest light we can see, more than thirteen billion years.", 1.0)],
      trans="dissolve:0.7", sfx={0.2: "pulse_hi"}),
 dict(id="S24", act=3, scene="scale", params=dict(stage="universe"),
      min_dur=12.0, lead=0.5, tail=1.4,
      lines=[L("Every image of the sky is a layered photograph of different pasts.", 0.7),
             L("There is no single 'now' out there to look at.", 0.6), L("There never was.", 1.4)],
      trans="dip:1.2",
      notes="HUMAN MOMENT: a figure before a screen; the signal arrival counter reads years."),

 # ---------------------------------------------------------------- ACT IV
 dict(id="S25", act=4, scene="card", params=dict(text="GRAVITY REWRITES THE STAGE", style="act", act_no="IV"),
      min_dur=4.5, lead=0.4, tail=0.3,
      lines=[L("Then Einstein asked a harder question.", 0.6), L("What happens to this map when gravity is present?", 0.9)],
      trans="cut"),
 dict(id="S26", act=4, scene="gravity_grid", params=dict(phase="flat_to_curved"),
      min_dur=11.0, lead=0.3, tail=0.6,
      lines=[L("His answer took ten years.", 0.7),
             L("Gravity is not a force pulling through space. It is the shape of space and time themselves.", 1.0)],
      trans="cut", sfx={2.5: "sub_swell"},
      notes="A flat grid bends into a well as a mass fades in."),
 dict(id="S27", act=4, scene="gravity_grid", params=dict(phase="equation"),
      min_dur=9.0, lead=0.3, tail=0.6,
      lines=[L("Mass tells spacetime how to curve.", 0.5), L("Curved spacetime tells mass how to move.", 1.0)],
      trans="cut", sfx={0.3: "ui_in"},
      notes="Einstein field equations: left side glows with the curvature, right side with the mass-energy."),
 dict(id="S28", act=4, scene="gravity_grid", params=dict(phase="orbit"),
      min_dur=9.0, lead=0.3, tail=0.8,
      lines=[L("A planet in orbit is not being pulled.", 0.5),
             L("It is travelling as straight as it can through a geometry that is bent.", 1.0)],
      trans="dissolve:1.0",
      notes="A small body follows a geodesic on the well; its path, lifted off the surface, is an ellipse."),
 dict(id="S29", act=4, scene="lensing", params=dict(),
      min_dur=12.0, lead=0.3, tail=0.8,
      lines=[L("Light bends too.", 0.6),
             L("A galaxy behind a massive cluster is smeared into arcs and rings: a lens made of pure gravity.", 1.0)],
      trans="cut", sfx={1.0: "whoosh_soft"},
      notes="A point-mass lens crosses in front of a background galaxy: arcs, then an Einstein ring (computed from the lens equation)."),
 dict(id="S30", act=4, scene="clock_tower", params=dict(),
      min_dur=14.0, lead=0.3, tail=1.2,
      lines=[L("And clocks run at different rates depending on where they sit in that geometry.", 0.6),
             L("Deeper in a gravitational well, time runs slower.", 0.7),
             L("In 2010, two atomic clocks, one raised just thirty-three centimeters above the other, measurably disagreed.", 1.3)],
      trans="dip:1.0", sfx={0.0: "tick_pair"},
      notes="Two clocks on a vertical scale; the lower one lags by an exaggerated, labelled amount. Caption: 33 cm — Chou et al., 2010."),

 # ---------------------------------------------------------------- ACT V
 dict(id="S31", act=5, scene="blackhole", params=dict(phase="approach"),
      min_dur=14.0, lead=1.5, tail=0.8,
      lines=[L("Compress enough mass into a small enough region, and there is a boundary from which no path leads back out. Not even for light.", 0.8),
             L("We call it the event horizon.", 1.2)],
      trans="cut", sfx={0.0: "drone_in"},
      notes="Long approach from far away: a dark ring grows against lensed stars; the disk resolves."),
 dict(id="S32", act=5, scene="blackhole", params=dict(phase="reveal"),
      min_dur=12.0, lead=0.3, tail=0.8,
      lines=[L("This image is computed, not painted.", 0.6),
             L("Every pixel is a path of light, traced through the geometry Karl Schwarzschild derived from Einstein's equations in 1916.", 1.0)],
      trans="cut",
      notes="Slow orbit; a thin caption notes: Schwarzschild metric · null geodesics · thin disk."),
 dict(id="S33", act=5, scene="blackhole", params=dict(phase="disk"),
      min_dur=12.0, lead=0.3, tail=0.8,
      lines=[L("Hot gas spirals inward in a thin disk.", 0.6),
             L("Light from the far side of the disk is bent up and over the hole, so you see what is behind it.", 1.0)],
      trans="cut",
      notes="Camera dips toward the disk plane; the far-side arc above the shadow becomes obvious."),
 dict(id="S34", act=5, scene="blackhole", params=dict(phase="doppler"),
      min_dur=12.0, lead=0.3, tail=0.8,
      lines=[L("The side rotating toward you is brighter.", 0.6),
             L("The gas there moves at a good fraction of the speed of light; its glow is beamed forward and shifted toward blue.", 1.0)],
      trans="cut",
      notes="Push-in on the bright approaching limb; labels: approaching / receding."),
 dict(id="S35", act=5, scene="blackhole", params=dict(phase="ring"),
      min_dur=14.0, lead=0.3, tail=0.8,
      lines=[L("And around the shadow, a thin bright ring: light that circled the black hole before escaping.", 0.8),
             L("In 2019, the Event Horizon Telescope saw that ring around the black hole in the galaxy M87; in 2022, around the one at the center of our own.", 1.2)],
      trans="cut", sfx={0.5: "data_tick"},
      notes="Close-up of the photon ring; a small inset reproduces the EHT ring diameter scale (≈5.2 Schwarzschild radii)."),
 dict(id="S36", act=5, scene="blackhole", params=dict(phase="fall"),
      min_dur=16.0, lead=0.3, tail=1.5,
      lines=[L("At the horizon, seen from far away, a falling clock seems to slow, and stop.", 0.9),
             L("For the one who falls, nothing special marks the crossing.", 0.8),
             L("Both descriptions are correct.", 0.7), L("There is no now they could share.", 1.5)],
      trans="dip:1.5", sfx={0.0: "tick_slow"},
      notes="HUMAN MOMENT: an astronaut silhouette drifting toward the horizon; its clock readout slows; ticks stretch."),

 # ---------------------------------------------------------------- ACT VI
 dict(id="S37", act=6, scene="card", params=dict(text="THEN QUANTUM PHYSICS ARRIVED", style="act", act_no="VI"),
      min_dur=4.5, lead=0.4, tail=0.3,
      lines=[L("While relativity was redrawing the large, a different revolution was dismantling the small.", 0.9)],
      trans="cut"),
 dict(id="S38", act=6, scene="orbital", params=dict(phase="not_planet"),
      min_dur=11.0, lead=0.3, tail=0.6,
      lines=[L("An electron in an atom is not a tiny planet on a tiny orbit.", 0.7),
             L("It is better described by a wave of possibility: a cloud whose shape is the solution of an equation.", 1.0)],
      trans="cut", sfx={2.0: "ui_out"},
      notes="A planetary 'atom' icon is drawn, then struck out; it dissolves into a sampled hydrogen probability cloud."),
 dict(id="S39", act=6, scene="orbital", params=dict(phase="interference"),
      min_dur=10.0, lead=0.3, tail=0.8,
      lines=[L("Where the wave is dense, the electron is likely to be found.", 0.6),
             L("Where it cancels itself, it is never found.", 0.6), L("Interference, not orbit.", 1.0)],
      trans="dissolve:1.0",
      notes="Orbitals morph 1s → 2p → 3d; nodal planes marked."),
 dict(id="S40", act=6, scene="double_slit", params=dict(),
      min_dur=14.0, lead=0.3, tail=0.8,
      lines=[L("A quantum system can be in a superposition: not here or there, but a precise blend of both, with amplitudes that add and subtract like waves.", 1.0),
             L("Measure it, and you get one definite answer.", 0.6),
             L("Repeat it, and the answers follow the probabilities the wave predicted.", 1.0)],
      trans="cut", sfx={0.0: "detector"},
      notes="Two-slit wave field; single detections accumulate on a screen into fringes that match |ψ|²."),
 dict(id="S41", act=6, scene="uncertainty", params=dict(),
      min_dur=12.0, lead=0.3, tail=1.2,
      lines=[L("And some pairs of questions cannot both have sharp answers.", 0.6),
             L("The more precisely a position is fixed, the less precisely momentum can be.", 0.6),
             L("This is not a limit of instruments. It is a property of waves.", 1.2)],
      trans="dip:1.0",
      notes="A wave packet and its Fourier transform: squeeze one, the other spreads. Δx·Δp ≥ ħ/2."),

 # ---------------------------------------------------------------- ACT VII
 dict(id="S42", act=7, scene="card", params=dict(text="ENTANGLEMENT", style="act", act_no="VII"),
      min_dur=4.0, lead=0.4, tail=0.3,
      lines=[L("Now take two particles, prepared together, so that their properties are linked.", 0.8)],
      trans="cut"),
 dict(id="S43", act=7, scene="entangle", params=dict(phase="separate"),
      min_dur=10.0, lead=0.3, tail=0.6,
      lines=[L("Send one to a laboratory on Earth.", 0.5), L("Send the other across the solar system.", 1.0)],
      trans="cut", sfx={1.0: "whoosh_soft"},
      notes="HUMAN MOMENT: two observers, one on Earth, one on a distant craft, each with a detector."),
 dict(id="S44", act=7, scene="entangle", params=dict(phase="measure"),
      min_dur=16.0, lead=0.3, tail=0.6,
      lines=[L("Measure each one, and its answer is random.", 0.6),
             L("Compare them, and they match, every time, in ways no story of hidden, pre-arranged values can reproduce.", 0.6),
             L("That is what Bell's theorem proves, and what experiments have confirmed, loophole by loophole.", 1.0)],
      trans="cut", sfx={0.0: "detector"},
      notes="Outcomes appear as random bits on both sides; the comparison column fills; the Bell correlation curve exceeds the classical bound."),
 dict(id="S45", act=7, scene="entangle", params=dict(phase="nosignal"),
      min_dur=14.0, lead=0.3, tail=1.2,
      lines=[L("But look carefully at what did not happen.", 0.7), L("Nothing travelled between them.", 0.7),
             L("No one on Earth can choose which answer the distant particle gives. So: no message, no signal, nothing faster than light.", 0.8),
             L("Entanglement is a correlation written into the state of the pair. It cannot carry a message.", 1.3)],
      trans="dip:1.0", sfx={1.5: "ui_out"},
      notes="A would-be 'signal' arrow is drawn and crossed out; the light cone remains the only causal path."),

 # ---------------------------------------------------------------- ACT VIII
 dict(id="S46", act=8, scene="card", params=dict(text="TWO GREAT THEORIES", style="act", act_no="VIII"),
      min_dur=4.0, lead=0.4, tail=0.3,
      lines=[L("So we arrive at the strangest situation in modern science.", 0.9)],
      trans="cut"),
 dict(id="S47", act=8, scene="split", params=dict(phase="gr"),
      min_dur=12.0, lead=0.3, tail=0.6,
      lines=[L("On one side, general relativity: gravity as geometry.", 0.6),
             L("It predicted the bending of starlight, the slowing of clocks, black holes, and the gravitational waves first detected in 2015.", 1.0)],
      trans="cut", sfx={0.3: "sub_swell"},
      notes="Left half: curved grid, orbit, a gravitational-wave chirp waveform."),
 dict(id="S48", act=8, scene="split", params=dict(phase="qft"),
      min_dur=12.0, lead=0.3, tail=0.6,
      lines=[L("On the other, quantum field theory: particles as excitations of fields filling all of space.", 0.6),
             L("It predicts the magnetism of the electron to twelve decimal places.", 1.0)],
      trans="cut", sfx={0.3: "pulse_hi"},
      notes="Right half: a field lattice with localized excitations; the g-factor digits count up."),
 dict(id="S49", act=8, scene="split", params=dict(phase="both"),
      min_dur=14.0, lead=0.3, tail=0.6,
      lines=[L("Each works, in its domain, to a precision that is almost absurd. But they speak different languages.", 0.8),
             L("In relativity, spacetime is a smooth, dynamic stage, shaped by the matter on it.", 0.5),
             L("In quantum theory, the stage is fixed, and the actors are uncertain.", 1.0)],
      trans="cut"),
 dict(id="S50", act=8, scene="split", params=dict(phase="clash"),
      min_dur=16.0, lead=0.3, tail=1.4,
      lines=[L("Try to make gravity itself quantum, the way the other forces are, and the calculations fill with infinities the usual methods cannot tame.", 0.8),
             L("At ordinary energies this is harmless: each theory is used where it applies.", 0.7),
             L("But at the center of a black hole, and in the first instant of the universe, both must matter at once.", 0.6),
             L("There, our best descriptions stop making predictions.", 1.4)],
      trans="dip:1.4", sfx={0.5: "drone_in", 9.0: "sub_drop"},
      notes="The two halves are pushed together; at the seam the grid tears into noise; the frame goes quiet."),

 # ---------------------------------------------------------------- ACT IX
 dict(id="S51", act=9, scene="frontier", params=dict(phase="question"),
      min_dur=9.0, lead=1.2, tail=1.0,
      lines=[L("What is reality made of, at the deepest level?", 1.4), L("We do not know.", 0.8), L("Not yet.", 1.2)],
      trans="cut",
      notes="Music drops to almost nothing. A single point of light in a dark field."),
 dict(id="S52", act=9, scene="frontier", params=dict(phase="candidates"),
      min_dur=16.0, lead=0.3, tail=0.8,
      lines=[L("There are serious candidates.", 0.6), L("String theory.", 0.6), L("Loop quantum gravity.", 0.6),
             L("Ideas in which space and time themselves emerge from something deeper, the way temperature emerges from the motion of molecules.", 1.0)],
      trans="cut", sfx={2.0: "ui_in", 4.0: "ui_in", 6.0: "ui_in"},
      notes="Three abstract sketches, each tagged ACTIVE RESEARCH: a vibrating loop, a spin network, points condensing into a grid."),
 dict(id="S53", act=9, scene="frontier", params=dict(phase="status"),
      min_dur=9.0, lead=0.3, tail=0.8,
      lines=[L("None of them has yet made a prediction that experiment has confirmed.", 0.6),
             L("They are not established physics. They are the frontier.", 1.0)],
      trans="cut",
      notes="Two columns: ESTABLISHED vs ACTIVE RESEARCH, with the film's claims sorted into each."),
 dict(id="S54", act=9, scene="frontier", params=dict(phase="established"),
      min_dur=18.0, lead=0.3, tail=1.4,
      lines=[L("What is established is this.", 0.8), L("There is no universal now.", 0.7),
             L("Time is local, and relative, and shaped by mass.", 0.7),
             L("At the smallest scales, reality is probabilistic, and correlated in ways that have no classical explanation.", 0.7),
             L("And our two best theories, each confirmed beyond reasonable doubt, do not yet fit together.", 1.4)],
      trans="dip:1.2"),

 # ---------------------------------------------------------------- FINAL
 dict(id="S55", act=10, scene="two_clocks", params=dict(mode="return"),
      min_dur=8.0, lead=0.8, tail=0.8,
      lines=[L("So return to the first clock.", 1.2), L("Are these two events happening at the same time?", 1.4)],
      trans="cut", sfx={0.0: "tick_loop"},
      notes="The opening frame, exactly. The clocks tick."),
 dict(id="S56", act=10, scene="final_zoom", params=dict(),
      min_dur=24.0, lead=0.3, tail=6.0,
      lines=[L("The question that seemed trivial was never trivial.", 0.7),
             L("It depends on where you stand, how you move, and what you are near.", 0.9),
             L("And the universe, as far as we can tell, keeps no single time for anyone.", 1.0)],
      trans="dip:2.0", sfx={0.0: "tick_loop", 6.0: "whoosh_long"},
      notes="A light pulse leaves one clock for the other. Pull back: Earth, Solar System, galaxy, the observable universe. Then black."),
 dict(id="S57", act=10, scene="card", params=dict(text="We do not yet know what the universe is made of.\nWe only know how astonishingly well our questions\nfit what we can observe.", style="quote"),
      min_dur=9.5, lead=0.0, tail=0.0, lines=[], trans="dip:1.5",
      notes="Silence."),
 dict(id="S58", act=10, scene="credits", params=dict(),
      min_dur=17.0, lead=0.0, tail=0.0, lines=[], trans="cut"),
]

def all_lines():
    for s in SHOTS:
        for i, ln in enumerate(s["lines"]):
            yield s["id"], i, ln

if __name__ == "__main__":
    n = sum(len(l["text"].split()) for _, _, l in all_lines())
    print(len(SHOTS), "shots;", sum(len(s['lines']) for s in SHOTS), "lines;", n, "words")
