import type { FamilyState } from "./types";

const now = Date.now();
const hoursAgo = (h: number) => new Date(now - h * 3600_000).toISOString();
const daysAgo = (d: number) => new Date(now - d * 86_400_000).toISOString();

export const initialFamilyState: FamilyState = {
  familyName: "Familia Rivas",
  houseName: "Casa de mamá",
  rooms: [
    { id: "room-living", name: "Salón", icon: "living-room" },
    { id: "room-bedroom", name: "Dormitorio", icon: "bedroom" },
    { id: "room-bathroom", name: "Baño", icon: "bathroom" },
    { id: "room-kitchen", name: "Cocina", icon: "kitchen" },
    { id: "room-hallway", name: "Pasillo", icon: "hallway" },
  ],
  sensors: [
    {
      id: "sensor-1",
      name: "Sensor Salón",
      roomId: "room-living",
      status: "online",
      battery: null,
      lastSeen: hoursAgo(0),
      firmware: "1.2.0",
    },
    {
      id: "sensor-2",
      name: "Sensor Dormitorio",
      roomId: "room-bedroom",
      status: "online",
      battery: 82,
      lastSeen: hoursAgo(0),
      firmware: "1.2.0",
    },
    {
      id: "sensor-3",
      name: "Sensor Baño",
      roomId: "room-bathroom",
      status: "online",
      battery: 54,
      lastSeen: hoursAgo(0),
      firmware: "1.2.0",
    },
    {
      id: "sensor-4",
      name: "Sensor Cocina",
      roomId: "room-kitchen",
      status: "offline",
      battery: 12,
      lastSeen: hoursAgo(6),
      firmware: "1.1.4",
    },
    {
      id: "sensor-5",
      name: "Sensor Pasillo",
      roomId: "room-hallway",
      status: "online",
      battery: null,
      lastSeen: hoursAgo(0),
      firmware: "1.2.0",
    },
  ],
  members: [
    {
      id: "member-you",
      name: "Tú",
      role: "admin",
      phone: "+34 600 000 000",
      avatarColor: "#2563eb",
      isEmergencyContact: true,
      escalationOrder: 1,
      isYou: true,
    },
    {
      id: "member-2",
      name: "Carla Rivas",
      role: "cuidador",
      phone: "+34 611 111 111",
      avatarColor: "#7c3aed",
      isEmergencyContact: true,
      escalationOrder: 2,
    },
    {
      id: "member-3",
      name: "Enfermería a domicilio",
      role: "cuidador",
      phone: "+34 900 222 333",
      avatarColor: "#0d9488",
      isEmergencyContact: true,
      escalationOrder: 3,
    },
  ],
  events: [
    {
      id: "event-1",
      roomId: "room-bathroom",
      sensorId: "sensor-3",
      detectedAt: daysAgo(2),
      status: "false_alarm",
      confidence: "media",
      resolvedAt: daysAgo(2),
      resolvedBy: "member-you",
    },
    {
      id: "event-2",
      roomId: "room-living",
      sensorId: "sensor-1",
      detectedAt: daysAgo(5),
      status: "confirmed_ok",
      confidence: "alta",
      resolvedAt: daysAgo(5),
      resolvedBy: "member-2",
    },
    {
      id: "event-3",
      roomId: "room-kitchen",
      sensorId: "sensor-4",
      detectedAt: daysAgo(9),
      status: "confirmed_fall",
      confidence: "alta",
      resolvedAt: daysAgo(9),
      resolvedBy: "member-you",
    },
  ],
  settings: {
    sensitivity: "media",
    doNotDisturbUntil: null,
    escalationTimeoutSeconds: 60,
    notifyPush: true,
    notifySms: true,
    notifyCall: true,
  },
};
